AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to Deploy EC2 with Milvus and ECR Access

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: 'c5n.xlarge'
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - c5n.xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Default: MilvusKeyPair
    Description: Name of an existing EC2 KeyPair to enable SSH access.
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MilvusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0427090fd1714168b  # Replace with the latest Ubuntu AMI in your region
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MilvusSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -e
            sudo yum update -y
            sudo yum install docker -y
            sudo service docker start
            sudo systemctl enable docker
            # Download the installation script
            sudo curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh -o standalone_embed.sh
            sudo standalone_embed.sh start

  MilvusSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Milvus EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 19530
          ToPort: 19530
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 19121
          ToPort: 19121
          CidrIp: 0.0.0.0/0

  EC2InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !ImportValue EC2ECRAccessRoleARN

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MilvusInstance.PublicIp
  InstanceId:
    Description: Instance ID of the EC2 instance
    Value: !Ref MilvusInstance
