namespace: ragenesis-dev

replicaCount: 1

image:
  repository: sjc.vultrcr.com/gendocapi/ragenesis-dev # todo: improve this regirstry name 
  tag: latest

imagePullSecretName: vultr-cr-credentials

dockerConfigJson: "eyJhdXRocyI6eyJzamMudnVsdHJjci5jb20iOnsiYXV0aCI6ImNtOWliM1FrWjJWdVpHOWpZWEJwSzJJeE5EQmtaR1ppTFRZNFl6SXROREEyTmkxaE9HRmxMV0l3TlRVeE9ERTBNV1V3WkRwWGVIQkljbEptUkc1Q1dsRldURWRHT1VaME4wdDNTRUYxYW5WRk5URm1XZz09In19fQ=="


clusterIssuer: letsencrypt #todo: improve issuer name
host: dev.api.genndoc.com  #your domain

service:
  port: 8501  
  targetPort: 8501

deployment:
  containerPort: 8501

ingress:
  servicePort: 8501

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi