AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EC2ECRAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: "EC2ECRAccessPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:BatchDeleteImage'
                  - 'ecr:BatchGetImage'
                  - 'ecr:CompleteLayerUpload'
                  - 'ecr:CreateRepository'
                  - 'ecr:DeleteLifecyclePolicy'
                  - 'ecr:DeleteRegistryPolicy'
                  - 'ecr:DeleteRepository'
                  - 'ecr:DeleteRepositoryPolicy'
                  - 'ecr:DescribeImageReplicationStatus'
                  - 'ecr:DescribeImageScanFindings'
                  - 'ecr:DescribeImages'
                  - 'ecr:DescribePullThroughCacheRules'
                  - 'ecr:DescribeRegistry'
                  - 'ecr:DescribeRepositories'
                  - 'ecr:GetAuthorizationToken'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:GetLifecyclePolicy'
                  - 'ecr:GetLifecyclePolicyPreview'
                  - 'ecr:GetRegistryPolicy'
                  - 'ecr:GetRegistryScanningConfiguration'
                  - 'ecr:GetRepositoryPolicy'
                  - 'ecr:InitiateLayerUpload'
                  - 'ecr:ListImages'
                  - 'ecr:ListTagsForResource'
                  - 'ecr:PutImage'
                  - 'ecr:PutImageScanningConfiguration'
                  - 'ecr:PutImageTagMutability'
                  - 'ecr:PutLifecyclePolicy'
                  - 'ecr:PutRegistryPolicy'
                  - 'ecr:PutRegistryScanningConfiguration'
                  - 'ecr:PutReplicationConfiguration'
                  - 'ecr:SetRepositoryPolicy'
                  - 'ecr:StartImageScan'
                  - 'ecr:StartLifecyclePolicyPreview'
                  - 'ecr:TagResource'
                  - 'ecr:UntagResource'
                  - 'ecr:UploadLayerPart'
                Resource: "*"

  EC2ECRAccessInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EC2ECRAccessRole

Outputs:
  EC2ECRAccessRoleARN:
    Value: !GetAtt EC2ECRAccessRole.Arn
    Description: IAM Role ARN for EC2 instance to access ECR
    Export:
      Name: EC2ECRAccessRoleARN
