version = 0.1
[dev.deploy.parameters]
stack_name = "ragenesis"
resolve_s3 = true
s3_prefix = "ragenesis"
region = "us-east-1"
profile = "janu-dev"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Prefix=\"app-ragenesis\" EnvironmentName=\"dev\""
image_repositories = []

[default.deploy.parameters]
stack_name = "ragenesis"
resolve_s3 = true
s3_prefix = "ragenesis"
region = "us-east-1"
profile = "janu-dev"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "Prefix=\"app-ragenesis\" EnvironmentName=\"dev\""
