AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties: 
      ServiceName: "MyStreamlitAppRunnerService"
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !ImportValue AppRunnerECRAccessRoleARN
        ImageRepository:
          ImageIdentifier: "975050138131.dkr.ecr.us-east-1.amazonaws.com/ragenesis:latest"
          ImageRepositoryType: "ECR"
      InstanceConfiguration:
        Cpu: "1 vCPU"
        Memory: "2 GB"
        # InstanceRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
      HealthCheckConfiguration:
        Protocol: "HTTP"
        Path: "/health"
        Interval: 10
        Timeout: 10
        HealthyThreshold: 3
        UnhealthyThreshold: 3
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: "DEFAULT"
      AutoScalingConfigurationArn: !Ref MyAutoScalingConfiguration

  MyAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: "MyAppRunnerAutoScaling"
      MaxConcurrency: 25
      MinSize: 1
      MaxSize: 5

Outputs:
  ServiceURL:
    Description: "URL for the deployed Streamlit application on AWS App Runner"
    Value: !GetAtt MyAppRunnerService.ServiceUrl