AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyAppRunnerService:
    Type: AWS::AppRunner::Service
    Properties: 
      ServiceName: "MyStreamlitAppRunnerService"
      SourceConfiguration:
        AuthenticationConfiguration:
          # Uncomment and set values if using a private repository
          ConnectionArn: arn:aws:codestar-connections:us-east-1:975050138131:connection/CONNECTION_ID
        ImageRepository:
          ImageIdentifier: "975050138131.dkr.ecr.us-east-1.amazonaws.com/ragenesis:latest"  # Your Docker image located in Amazon ECR
          ImageRepositoryType: "ECR"  # Using ECR for images in Elastic Container Registry
        Port: "8501"  # Streamlit's default port
      InstanceConfiguration:
        Cpu: "1 vCPU"  # Adjust to your requirements: 1 vCPU, 2 vCPU, 4 vCPU
        Memory: "2 GB"  # Adjust to your requirements: 2 GB, 4 GB
      HealthCheckConfiguration:
        Protocol: "HTTP"
        Path: "/health"  # Implement a health check endpoint if /health is not yet available
        Interval: 10  # Time between health checks in seconds
        Timeout: 5  # Time to wait for a response from the health check in seconds
        HealthyThreshold: 3  # Number of consecutive checks before considering the service healthy
        UnhealthyThreshold: 3  # Number of consecutive checks before considering the service unhealthy
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: "DEFAULT"  # Use "VPC" if you want to use a VPC Connector
          # VpcConnectorArn: "YOUR_VPC_CONNECTOR_ARN"  # Uncomment if using a VPC Connector
      AutoScalingConfigurationArn: !Ref MyAutoScalingConfiguration

  MyAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: "MyAppRunnerAutoScaling"
      MaxConcurrency: 25  # Maximum number of concurrent requests an instance can handle
      MinSize: 1  # Minimum number of instances
      MaxSize: 5  # Maximum number of instances

Outputs:
  ServiceURL:
    Description: "URL for the deployed Streamlit application on AWS App Runner"
    Value: !GetAtt MyAppRunnerService.ServiceUrl
